export const KEY = "store_command_center_v4";
export const nav = [["home","Home","⌂"],["next","What’s Next","→"],["tasks","Tasks","✓"],["dates","Dates","◫"],["handoff","Handoff","✎"],["more","More","•••"]];
export const priorities = ["Critical","High","Normal","Low"];
export const statuses = ["Not Started","In Progress","Blocked","Skipped","Completed"];
export const shifts = ["Open","Mid","Close","Truck Day"];
export const departments = ["Manager","Center Store","Front","Cooler","Kitchen","Exterior","Whole Store"];
export const uid=(p="item")=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
export const today=()=>{const n=new Date();return new Date(n.getTime()-n.getTimezoneOffset()*60000).toISOString().slice(0,10)};
export const plusDays=(d)=>{const n=new Date();n.setDate(n.getDate()+d);return new Date(n.getTime()-n.getTimezoneOffset()*60000).toISOString().slice(0,10)};
export const niceDate=(v)=>v?new Date(`${v}T12:00:00`).toLocaleDateString([],{month:"short",day:"numeric"}):"No date";
export const niceTime=(v)=>v?new Date(`2000-01-01T${v}:00`).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"Any time";
export const dueAt=(t)=>t.dueDate?new Date(`${t.dueDate}T${t.dueTime||"23:59"}:00`).getTime():Infinity;
export function taskScore(t){if(["Completed","Skipped"].includes(t.status))return-9999;if(t.status==="Blocked")return-100;const p={Critical:120,High:80,Normal:40,Low:10}[t.priority]||20,m=(dueAt(t)-Date.now())/60000,u=m<0?180:m<=60?120:m<=180?80:m<=720?40:0;return p+u+(t.status==="In Progress"?90:0)+(Number(t.estimate)<=10?18:0)}
export function taskReason(t){const m=(dueAt(t)-Date.now())/60000;if(t.status==="In Progress")return"You already started it. Finishing beats creating another half-done mystery.";if(m<0)return`It is overdue and marked ${t.priority.toLowerCase()} priority.`;if(m<=60)return`It is due within an hour and should take about ${t.estimate} minutes.`;if(t.priority==="Critical")return"It is critical and should be protected before lower-impact work.";if(Number(t.estimate)<=10)return"It is a quick win that clears an important item from the board.";return"It is the best combination of urgency, priority, and impact right now."}
export function dateInfo(i){if(i.status==="Handled")return{label:"Handled",tone:"success",rank:99};const d=Math.round((new Date(`${i.expirationDate}T12:00:00`)-new Date(`${today()}T12:00:00`))/86400000);if(d<0)return{label:"Expired",tone:"danger",rank:0};if(d===0)return{label:"Due today",tone:"danger",rank:1};if(d<=3)return{label:`${d} day${d===1?"":"s"}`,tone:"warning",rank:2};if(d<=7)return{label:`${d} days`,tone:"warning",rank:3};return{label:"Safe",tone:"success",rank:5}}
export function defaults(){return{profile:{name:"Jamison",role:"Center Store Manager",store:"Store 2593",shift:"Open"},tasks:[
{id:uid("task"),title:"Complete opening manager walk",description:"Check exterior, restrooms, counter, coffee, cooler, kitchen, and visible standards.",department:"Whole Store",assignee:"Jamison",shift:"Open",dueDate:today(),dueTime:"08:00",estimate:20,priority:"Critical",status:"Not Started",waitingOn:""},
{id:uid("task"),title:"Review Date Watch",description:"Pull expired product and flag anything due within three days.",department:"Center Store",assignee:"Jamison",shift:"Open",dueDate:today(),dueTime:"09:00",estimate:15,priority:"High",status:"Not Started",waitingOn:""},
{id:uid("task"),title:"Cigarette audit",description:"Verify counts, outs, and backbar condition.",department:"Front",assignee:"Jamison",shift:"Open",dueDate:today(),dueTime:"10:00",estimate:15,priority:"High",status:"Not Started",waitingOn:""},
{id:uid("task"),title:"Pick one visible win",description:"Make one high-traffic area noticeably better before leaving.",department:"Center Store",assignee:"Jamison",shift:"Open",dueDate:today(),dueTime:"13:30",estimate:25,priority:"Normal",status:"Not Started",waitingOn:""}],dates:[
{id:uid("date"),name:"Half & Half Creamer",area:"Dairy",location:"Open-air cooler",quantity:4,expirationDate:today(),status:"Watching",notes:"Check today."},
{id:uid("date"),name:"French Vanilla Creamer",area:"Dairy",location:"Open-air cooler",quantity:4,expirationDate:plusDays(2),status:"Watching",notes:"Watch pull timing."},
{id:uid("date"),name:"Ribbon Pepperoni",area:"Kitchen",location:"Walk-in",quantity:3,expirationDate:plusDays(7),status:"Watching",notes:"Low count."}],handoffs:[{id:uid("handoff"),author:"Previous Shift",shift:"Close",category:"Needs Attention",priority:"High",message:"Cooler recovery is partly finished. Energy drinks and water still need attention.",status:"Open",createdAt:new Date().toISOString(),acknowledgedBy:"",resolvedBy:""}],reminders:[{id:uid("rem"),text:"Review change order and receiving paperwork",done:false},{id:uid("rem"),text:"Check lottery before leaving",done:false}],truck:["Clear receiving path","Assign areas","Receive and check damage","Move cold freight first","Work visible outs","Break down cardboard","Final backstock check"].map(title=>({id:uid("truck"),title,done:false})),activity:[]}}
export function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaults()}catch{return defaults()}}
